var PlayLists = {
  lists: [
    {"title":"RPG", "singer":"sekai no owari"},
    {"title":"残酷な天使のテーゼ", "singer":"高橋 洋子"},
    {"title":"Rain", "singer":"sekai no owari"},
    {"title":"Dragon Night", "singer":"sekai no owari"},
    {"title":"幻の命", "singer":"sekai no owari"},
    {"title":"Happy End", "singer":"Back Number"},
    {"title":"himawari", "singer":"Mr.Children"},
    {"title":"hanabi", "singer":"Mr.Children"},
    {"title":"tears", "singer":"X-Japan"},
    {"title":"Soup", "singer":"藤原さくら"},
    {"title":"好きよ好きよ好きよ", "singer":"藤原さくら"},
    {"title":"PIKANCHI", "singer":"嵐"},
    {"title":"WISH", "singer":"嵐"},
    {"title":"きっと大丈夫", "singer":"嵐"},
    {"title":"A.RA.SHI", "singer":"嵐"},
    {"title":"Happiness", "singer":"嵐"},
    {"title":"Beautiful days", "singer":"嵐"},
    {"title":"Face Down", "singer":"嵐"},
    {"title":"Feel Your Breeze", "singer":"V6"},
    {"title":"恋", "singer":"星野源"},
    {"title":"One Love", "singer":"嵐"},
    {"title":"Love so sweet", "singer":"嵐"}
  ]
}

var Lyrics = {
  lyric : [
    {"title": "RPG", "lines": [
      {"lyric":"空は青く澄み渡り","start":"0","end":"10"},
      {"lyric":"海を目指して歩く","start":"10","end":"13"},
      {"lyric":"怖いものなんてない","start":"13","end":"17"},
      {"lyric":"僕らはもう1人じゃない","start":"17","end":"22"},
      {"lyric":"大切な何かが壊れたあの夜に","start":"22","end":"29"},
      {"lyric":"僕は星を探して1人で歩いていた","start":"29","end":"37"},
      {"lyric":"ペルセウス座流星群","start":"37","end":"40"},
      {"lyric":"君も見てただろうか","start":"40","end":"43"},
      {"lyric":"僕は元気でやってるよ","start":"43","end":"47"},
      {"lyric":"君は今どこにいるの","start":"47","end":"51"},
      {"lyric":"「方法」という悪魔に","start":"51","end":"55"},
      {"lyric":"取り憑かれないで","start":"55","end":"58"},
      {"lyric":"「目的」という大事なものを思い出して","start":"58","end":"69"},
      {"lyric":"空は青く澄み渡り","start":"69","end":"72"},
      {"lyric":"海を目指して歩く","start":"72","end":"76"},
      {"lyric":"怖いものなんてない","start":"76","end":"79"},
      {"lyric":"僕らはもう1人じゃない","start":"79","end":"83"},
      {"lyric":"空は青く澄み渡り","start":"83","end":"87"},
      {"lyric":"海を目指して歩く","start":"87","end":"90"},
      {"lyric":"怖くても大丈夫","start":"90","end":"93"},
      {"lyric":"僕らはもう1人じゃない","start":"93","end":"125"},
      {"lyric":"大切な何かが壊れたあの夜に","start":"125","end":"132"},
      {"lyric":"僕は君を探して1人で歩いていた","start":"132","end":"139"},
      {"lyric":"あの日から僕らは1人で海を目指す","start":"139","end":"146"},
      {"lyric":"約束のあの場所で必ずまた会おうと","start":"146","end":"153"},
      {"lyric":"「世間」という悪魔に惑わされないで","start":"153","end":"161"},
      {"lyric":"「自分」だけが決めた答えを思い出して","start":"161","end":"171"},
      {"lyric":"空は青く澄み渡り","start":"171","end":"175"},
      {"lyric":"海を目指して歩く","start":"175","end":"179"},
      {"lyric":"怖いものなんてない","start":"179","end":"182"},
      {"lyric":"僕らはもう1人じゃない","start":"182","end":"186"},
      {"lyric":"空は青く澄み渡り","start":"186","end":"189"},
      {"lyric":"海を目指して歩く","start":"189","end":"193"},
      {"lyric":"怖くても大丈夫","start":"193","end":"196"},
      {"lyric":"僕らはもう1人じゃない","start":"196","end":"214"},
      {"lyric":"煌めきのような","start":"214","end":"218"},
      {"lyric":"人生の中で君に出会えて","start":"218","end":"225"},
      {"lyric":"僕は本当に良かった","start":"225","end":"232"},
      {"lyric":"街を抜け海に出たら","start":"232","end":"236"},
      {"lyric":"次はどこを目指そうか","start":"236","end":"240"},
      {"lyric":"僕らはまた出かけよう","start":"240","end":"242"},
      {"lyric":"愛しいこの世界を","start":"242","end":"248"},
      {"lyric":"空は青く澄み渡り","start":"248","end":"252"},
      {"lyric":"海を目指して歩く","start":"252","end":"255"},
      {"lyric":"怖いものなんてない","start":"255","end":"258"},
      {"lyric":"僕らはもう1人じゃない","start":"258","end":"262"},
      {"lyric":"空は青く澄み渡り","start":"262","end":"266"},
      {"lyric":"海を目指して歩く","start":"266","end":"269"},
      {"lyric":"怖くても大丈夫","start":"269","end":"272"},
      {"lyric":"僕らはもう1人じゃない","start":"272","end":"286"}
    ]},
    {"title": "残酷な天使", "lines": [
      {"lyric":"残酷な天使のように","start":"0","end":"10"},
      {"lyric":"少年よ神話になれ","start":"10","end":"26"},
      {"lyric":"青い風が今胸のドアを叩いても","start":"26","end":"33"},
      {"lyric":"私だけをただ見つめて微笑んでるあなた","start":"33","end":"40"},
      {"lyric":"そっとふれるものもとめることに夢中で","start":"40","end":"47"},
      {"lyric":"運命さえまだ知らないいたいけな瞳","start":"47","end":"55"},
      {"lyric":"だけどいつか気付くでしょうその背中には","start":"55","end":"62"},
      {"lyric":"はるか未来めざすための羽根があること","start":"62","end":"70"},
      {"lyric":"残酷な天使のテーゼ","start":"70","end":"74"},
      {"lyric":"窓辺からやがて飛び立つ","start":"74","end":"77"},
      {"lyric":"ほとばしる熱いパトスで","start":"77","end":"81"},
      {"lyric":"思い出を裏切るなら","start":"81","end":"85"},
      {"lyric":"この宇宙を抱いて輝く","start":"85","end":"89"},
      {"lyric":"少年よ神話になれ!","start":"89","end":"138"},
      {"lyric":"ずっと眠ってる私の愛の揺りかご","start":"138","end":"145"},
      {"lyric":"あなただけが夢の使者に呼ばれる朝がくる","start":"145","end":"153"},
      {"lyric":"細い首筋を月あかりが映してる","start":"153","end":"159"},
      {"lyric":"世界中の時を止めて閉じこめたいけど","start":"159","end":"167"},
      {"lyric":"もしもふたり逢えたことに意味があるなら","start":"167","end":"175"},
      {"lyric":"私はそう自由を知るためのバイブル","start":"175","end":"182"},
      {"lyric":"残酷な天使のテーゼ","start":"182","end":"186"},
      {"lyric":"悲しみがそしてはじまる","start":"186","end":"190"},
      {"lyric":"抱きしめた命のかたち","start":"190","end":"194"},
      {"lyric":"その夢に目覚めたとき","start":"194","end":"198"},
      {"lyric":"誰よりも光を放つ","start":"198","end":"201"},
      {"lyric":"少年よ神話になれ","start":"201","end":"205"},
      {"lyric":"人は愛をつむぎながら歴史をつくる","start":"205","end":"212"},
      {"lyric":"女神なんてなれないまま私は生きる","start":"212","end":"220"},
      {"lyric":"残酷な天使のテーゼ","start":"220","end":"223"},
      {"lyric":"窓辺からやがて飛び立つ","start":"223","end":"227"},
      {"lyric":"ほとばしる熱いパトスで","start":"227","end":"231"},
      {"lyric":"思い出を裏切るなら","start":"231","end":"235"},
      {"lyric":"この宇宙を抱いて輝く","start":"235","end":"239"},
      {"lyric":"少年よ神話になれ!","start":"239","end":"248"}
    ]}
  ]
}
