var PlayLists = {
  lists: [
    {"title":"RPG", "singer":"sekai no owari"},
    {"title":"残酷な天使のテーゼ", "singer":"高橋 洋子"},
    {"title":"Rain", "singer":"sekai no owari"},
    {"title":"Dragon Night", "singer":"sekai no owari"},
    {"title":"幻の命", "singer":"sekai no owari"},
    {"title":"Happy End", "singer":"Back Number"},
    {"title":"himawari", "singer":"Mr.Children"},
    {"title":"hanabi", "singer":"Mr.Children"},
    {"title":"tears", "singer":"X-Japan"},
    {"title":"Soup", "singer":"藤原さくら"},
    {"title":"好きよ好きよ好きよ", "singer":"藤原さくら"},
    {"title":"PIKANCHI", "singer":"嵐"},
    {"title":"WISH", "singer":"嵐"},
    {"title":"きっと大丈夫", "singer":"嵐"},
    {"title":"A.RA.SHI", "singer":"嵐"},
    {"title":"Happiness", "singer":"嵐"},
    {"title":"Beautiful days", "singer":"嵐"},
    {"title":"Face Down", "singer":"嵐"},
    {"title":"Feel Your Breeze", "singer":"V6"},
    {"title":"恋", "singer":"星野源"},
    {"title":"One Love", "singer":"嵐"},
    {"title":"Love so sweet", "singer":"嵐"},
    {"title":"世界はそれを愛と呼ぶんだぜ", "singer":"サンボマスター"},
  ]
}

var Lyrics = {
  lyric : [
    //0
    {"title": "RPG", "lines": [
      {"lyric":"空は青く澄み渡り","start":"0","end":"10"},
      {"lyric":"海を目指して歩く","start":"10","end":"13"},
      {"lyric":"怖いものなんてない","start":"13","end":"17"},
      {"lyric":"僕らはもう1人じゃない","start":"17","end":"22"},
      {"lyric":"大切な何かが壊れたあの夜に","start":"22","end":"29"},
      {"lyric":"僕は星を探して1人で歩いていた","start":"29","end":"37"},
      {"lyric":"ペルセウス座流星群","start":"37","end":"40"},
      {"lyric":"君も見てただろうか","start":"40","end":"43"},
      {"lyric":"僕は元気でやってるよ","start":"43","end":"47"},
      {"lyric":"君は今どこにいるの","start":"47","end":"51"},
      {"lyric":"「方法」という悪魔に","start":"51","end":"55"},
      {"lyric":"取り憑かれないで","start":"55","end":"58"},
      {"lyric":"「目的」という大事なものを思い出して","start":"58","end":"69"},
      {"lyric":"空は青く澄み渡り","start":"69","end":"72"},
      {"lyric":"海を目指して歩く","start":"72","end":"76"},
      {"lyric":"怖いものなんてない","start":"76","end":"79"},
      {"lyric":"僕らはもう1人じゃない","start":"79","end":"83"},
      {"lyric":"空は青く澄み渡り","start":"83","end":"87"},
      {"lyric":"海を目指して歩く","start":"87","end":"90"},
      {"lyric":"怖くても大丈夫","start":"90","end":"93"},
      {"lyric":"僕らはもう1人じゃない","start":"93","end":"125"},
      {"lyric":"大切な何かが壊れたあの夜に","start":"125","end":"132"},
      {"lyric":"僕は君を探して1人で歩いていた","start":"132","end":"139"},
      {"lyric":"あの日から僕らは1人で海を目指す","start":"139","end":"146"},
      {"lyric":"約束のあの場所で必ずまた会おうと","start":"146","end":"153"},
      {"lyric":"「世間」という悪魔に惑わされないで","start":"153","end":"161"},
      {"lyric":"「自分」だけが決めた答えを思い出して","start":"161","end":"171"},
      {"lyric":"空は青く澄み渡り","start":"171","end":"175"},
      {"lyric":"海を目指して歩く","start":"175","end":"179"},
      {"lyric":"怖いものなんてない","start":"179","end":"182"},
      {"lyric":"僕らはもう1人じゃない","start":"182","end":"186"},
      {"lyric":"空は青く澄み渡り","start":"186","end":"189"},
      {"lyric":"海を目指して歩く","start":"189","end":"193"},
      {"lyric":"怖くても大丈夫","start":"193","end":"196"},
      {"lyric":"僕らはもう1人じゃない","start":"196","end":"214"},
      {"lyric":"煌めきのような","start":"214","end":"218"},
      {"lyric":"人生の中で君に出会えて","start":"218","end":"225"},
      {"lyric":"僕は本当に良かった","start":"225","end":"232"},
      {"lyric":"街を抜け海に出たら","start":"232","end":"236"},
      {"lyric":"次はどこを目指そうか","start":"236","end":"240"},
      {"lyric":"僕らはまた出かけよう","start":"240","end":"242"},
      {"lyric":"愛しいこの世界を","start":"242","end":"248"},
      {"lyric":"空は青く澄み渡り","start":"248","end":"252"},
      {"lyric":"海を目指して歩く","start":"252","end":"255"},
      {"lyric":"怖いものなんてない","start":"255","end":"258"},
      {"lyric":"僕らはもう1人じゃない","start":"258","end":"262"},
      {"lyric":"空は青く澄み渡り","start":"262","end":"266"},
      {"lyric":"海を目指して歩く","start":"266","end":"269"},
      {"lyric":"怖くても大丈夫","start":"269","end":"272"},
      {"lyric":"僕らはもう1人じゃない","start":"272","end":"286"}
    ]},
    //1
    {"title": "残酷な天使", "lines": [
      {"lyric":"残酷な天使のように","start":"0","end":"10"},
      {"lyric":"少年よ神話になれ","start":"10","end":"26"},
      {"lyric":"青い風が今胸のドアを叩いても","start":"26","end":"33"},
      {"lyric":"私だけをただ見つめて微笑んでるあなた","start":"33","end":"40"},
      {"lyric":"そっとふれるものもとめることに夢中で","start":"40","end":"47"},
      {"lyric":"運命さえまだ知らないいたいけな瞳","start":"47","end":"55"},
      {"lyric":"だけどいつか気付くでしょうその背中には","start":"55","end":"62"},
      {"lyric":"はるか未来めざすための羽根があること","start":"62","end":"70"},
      {"lyric":"残酷な天使のテーゼ","start":"70","end":"74"},
      {"lyric":"窓辺からやがて飛び立つ","start":"74","end":"77"},
      {"lyric":"ほとばしる熱いパトスで","start":"77","end":"81"},
      {"lyric":"思い出を裏切るなら","start":"81","end":"85"},
      {"lyric":"この宇宙を抱いて輝く","start":"85","end":"89"},
      {"lyric":"少年よ神話になれ!","start":"89","end":"138"},
      {"lyric":"ずっと眠ってる私の愛の揺りかご","start":"138","end":"145"},
      {"lyric":"あなただけが夢の使者に呼ばれる朝がくる","start":"145","end":"153"},
      {"lyric":"細い首筋を月あかりが映してる","start":"153","end":"159"},
      {"lyric":"世界中の時を止めて閉じこめたいけど","start":"159","end":"167"},
      {"lyric":"もしもふたり逢えたことに意味があるなら","start":"167","end":"175"},
      {"lyric":"私はそう自由を知るためのバイブル","start":"175","end":"182"},
      {"lyric":"残酷な天使のテーゼ","start":"182","end":"186"},
      {"lyric":"悲しみがそしてはじまる","start":"186","end":"190"},
      {"lyric":"抱きしめた命のかたち","start":"190","end":"194"},
      {"lyric":"その夢に目覚めたとき","start":"194","end":"198"},
      {"lyric":"誰よりも光を放つ","start":"198","end":"201"},
      {"lyric":"少年よ神話になれ","start":"201","end":"205"},
      {"lyric":"人は愛をつむぎながら歴史をつくる","start":"205","end":"212"},
      {"lyric":"女神なんてなれないまま私は生きる","start":"212","end":"220"},
      {"lyric":"残酷な天使のテーゼ","start":"220","end":"223"},
      {"lyric":"窓辺からやがて飛び立つ","start":"223","end":"227"},
      {"lyric":"ほとばしる熱いパトスで","start":"227","end":"231"},
      {"lyric":"思い出を裏切るなら","start":"231","end":"235"},
      {"lyric":"この宇宙を抱いて輝く","start":"235","end":"239"},
      {"lyric":"少年よ神話になれ!","start":"239","end":"248"}
    ]},
    //2
    {"title": "Rain", "lines": [
      {"lyric":"魔法はいつか解けると僕らは知ってる","start":"0","end":"12"},
      {"lyric":"月が咲いて太陽が今枯れた","start":"12","end":"22"},
      {"lyric":"傘を差しだす君に映る僕は濡れてない","start":"22","end":"31"},
      {"lyric":"水たまりに映る僕は雨に濡れてた","start":"31","end":"41"},
      {"lyric":"幸せなような涙が出そうな","start":"41","end":"46"},
      {"lyric":"この気持ちはなんて言うんだろう","start":"46","end":"51"},
      {"lyric":"ファフロツキーズの夢を見て起きた","start":"51","end":"55"},
      {"lyric":"涙が頬で乾いていた","start":"55","end":"62"},
      {"lyric":"虹が架かる空には雨が降ってたんだ","start":"62","end":"73"},
      {"lyric":"虹はいずれ消えるけど雨は","start":"73","end":"77"},
      {"lyric":"草木を育ててゆくんだ","start":"77","end":"82"},
      {"lyric":"虹が架かる空には雨が降ってたんだ","start":"82","end":"92"},
      {"lyric":"いつか虹が消えてもずっと","start":"92","end":"97"},
      {"lyric":"僕らは空を見上げる","start":"97","end":"112"},
      {"lyric":"真っ白な夜に遠くを走る汽車の影","start":"112","end":"122"},
      {"lyric":"静寂と僕ら残して過ぎ去っていく","start":"122","end":"131"},
      {"lyric":"逃げ出したいような心躍るような","start":"131","end":"137"},
      {"lyric":"この気持ちはなんて言うんだろう","start":"137","end":"141"},
      {"lyric":"鏡の前で顔をそむけたのは","start":"141","end":"146"},
      {"lyric":"ずっと昔のことのようで","start":"146","end":"153"},
      {"lyric":"虹が架かる空には雨が降ってたんだ","start":"153","end":"163"},
      {"lyric":"虹はいずれ消えるけど雨は","start":"163","end":"168"},
      {"lyric":"草木を育てていたんだ","start":"168","end":"172"},
      {"lyric":"虹が架かる空には雨が降ってたんだ","start":"172","end":"183"},
      {"lyric":"忘れないよこんな雨の日に","start":"183","end":"188"},
      {"lyric":"空を見上げてきたこと","start":"188","end":"224"},
      {"lyric":"虹が架かる空には雨が降ってたんだ","start":"224","end":"235"},
      {"lyric":"虹はいずれ消えるけど雨は","start":"235","end":"239"},
      {"lyric":"草木を育ててゆくんだ","start":"239","end":"243"},
      {"lyric":"虹が架かる空には雨が降ってたんだ","start":"243","end":"254"},
      {"lyric":"いつか虹が消えてもずっと","start":"254","end":"259"},
      {"lyric":"僕らは空を見上げる","start":"259","end":"263"},
      {"lyric":"雨が止んだ庭に花が咲いてたんだ","start":"263","end":"278"},
      {"lyric":"きっともう大丈夫","start":"278","end":"283"},
      {"lyric":"そうだ次の雨の日のために","start":"283","end":"288"},
      {"lyric":"傘を探しに行こう","start":"288","end":"306"}
    ]},
    //3
    {"title": "残酷な天使", "lines": []},
    //4
    {"title": "残酷な天使", "lines": []},
    //5
    {"title": "Happy End", "lines": [
      {"lyric":"さよならが喉の奥に","start":"0","end":"24"},
      {"lyric":"つっかえてしまって","start":"24","end":"27"},
      {"lyric":"咳をするみたいに","start":"27","end":"30"},
      {"lyric":"ありがとうって言ったの","start":"30","end":"34"},
      {"lyric":"次の言葉はどこかと","start":"34","end":"37"},
      {"lyric":"ポケットを探しても","start":"37","end":"40"},
      {"lyric":"見つかるのはあなたを好きな私だけ","start":"40","end":"46"},
      {"lyric":"平気よ大丈夫だよ","start":"46","end":"50"},
      {"lyric":"優しくなれたと思って","start":"50","end":"53"},
      {"lyric":"願いに変わって最後は嘘になって","start":"53","end":"58"},
      {"lyric":"青いまま枯れてゆく","start":"58","end":"61"},
      {"lyric":"あなたを好きなままで消えてゆく","start":"61","end":"66"},
      {"lyric":"私みたいと手に取って","start":"66","end":"71"},
      {"lyric":"奥にあった想いと一緒に","start":"71","end":"74"},
      {"lyric":"握り潰したの","start":"74","end":"77"},
      {"lyric":"大丈夫大丈夫","start":"77","end":"83"},
      {"lyric":"今すぐに抱きしめて","start":"83","end":"86"},
      {"lyric":"私がいれば何もいらないと","start":"86","end":"91"},
      {"lyric":"それだけ言ってキスをして","start":"91","end":"96"},
      {"lyric":"なんてね嘘だよごめんね","start":"96","end":"109"},
      {"lyric":"こんな時思い出す事じゃ","start":"109","end":"112"},
      {"lyric":"ないとは思うんだけど","start":"112","end":"115"},
      {"lyric":"一人にしないよって","start":"115","end":"117"},
      {"lyric":"あれ実は嬉しかったよ","start":"117","end":"121"},
      {"lyric":"あなたが勇気を出して","start":"121","end":"125"},
      {"lyric":"初めて電話をくれた","start":"125","end":"127"},
      {"lyric":"あの夜の私と何が違うんだろう","start":"127","end":"134"},
      {"lyric":"どれだけ離れていても","start":"134","end":"137"},
      {"lyric":"どんなに会えなくても","start":"137","end":"140"},
      {"lyric":"気持ちが変わらないから","start":"140","end":"143"},
      {"lyric":"ここにいるのに","start":"143","end":"145"},
      {"lyric":"青いまま枯れてゆく","start":"145","end":"148"},
      {"lyric":"あなたを好きなままで消えてゆく","start":"148","end":"153"},
      {"lyric":"私をずっと覚えていて","start":"153","end":"158"},
      {"lyric":"なんてね嘘だよ元気でいてね","start":"158","end":"193"},
      {"lyric":"泣かない私に少し","start":"193","end":"196"},
      {"lyric":"ほっとした顔のあなた","start":"196","end":"199"},
      {"lyric":"相変わらず暢気ねそこも大好きよ","start":"199","end":"208"},
      {"lyric":"気が付けば横にいて","start":"208","end":"210"},
      {"lyric":"別に君のままでいいのになんて","start":"210","end":"216"},
      {"lyric":"勝手に涙拭いたくせに","start":"216","end":"221"},
      {"lyric":"見える全部聴こえる全て","start":"221","end":"224"},
      {"lyric":"色付けたくせに","start":"224","end":"226"},
      {"lyric":"青いまま枯れてゆく","start":"226","end":"229"},
      {"lyric":"あなたを好きなままで消えてゆく","start":"229","end":"234"},
      {"lyric":"私みたいと手に取って","start":"234","end":"240"},
      {"lyric":"奥にあった想いと一緒に","start":"240","end":"243"},
      {"lyric":"握り潰したの","start":"243","end":"245"},
      {"lyric":"大丈夫 大丈夫","start":"245","end":"251"},
      {"lyric":"今すぐに抱きしめて","start":"251","end":"254"},
      {"lyric":"私がいれば何もいらないと","start":"254","end":"259"},
      {"lyric":"そう言ってもう離さないで","start":"259","end":"264"},
      {"lyric":"なんてね 嘘だよ さよなら","start":"264","end":"313"}
    ]},
    //6
    {"title": "残酷な天使", "lines": []},
    //7
    {"title": "残酷な天使", "lines": []},
    //8
    {"title": "tears", "lines": [
      {"lyric":"何處に行けばいい貴方と離れて","start":"0","end":"44"},
      {"lyric":"今は過ぎ去った時流に問い卦けて","start":"44","end":"58"},
      {"lyric":"長すぎた夜に旅立ちを夢見た","start":"58","end":"71"},
      {"lyric":"異國の空見つめて孤獨を抱きしめた","start":"71","end":"83"},
      {"lyric":"流れゐ淚を時代の風に重ねて","start":"83","end":"96"},
      {"lyric":"終わらない貴女の吐息を感じて","start":"96","end":"107"},
      {"lyric":"Dry your tears with love","start":"107","end":"114"},
      {"lyric":"Dry your tears with love","start":"114","end":"137"},
      {"lyric":"Loneliness your silent whisper","start":"137","end":"144"},
      {"lyric":"Fills a river of tears through the night","start":"144","end":"150"},
      {"lyric":"Memory you never let me cry","start":"150","end":"156"},
      {"lyric":"And you, You never said goodbye","start":"156","end":"163"},
      {"lyric":"Sometimes our tears blinded the love","start":"163","end":"170"},
      {"lyric":"We lost our dreams along the way","start":"170","end":"176"},
      {"lyric":"But I never thought you'd trade your soul to the fates","start":"176","end":"181"},
      {"lyric":"Never thought you'd leave me alone","start":"181","end":"192"},
      {"lyric":"Time through the rain has set me free","start":"192","end":"199"},
      {"lyric":"Sands of time will keep your memory","start":"199","end":"205"},
      {"lyric":"Love everlasting fades away","start":"205","end":"212"},
      {"lyric":"Alive within your breathless heart","start":"212","end":"216"},
      {"lyric":"Dry your tears with love","start":"216","end":"222"},
      {"lyric":"Dry your tears with love","start":"222","end":"282"},
      {"lyric":"流れる淚を時代の風に重ねて","start":"282","end":"295"},
      {"lyric":"終わらない悲しみを靑い薔薇に變えて","start":"295","end":"306"},
      {"lyric":"Dry your tears with love","start":"306","end":"312"},
      {"lyric":"Dry your tears with love","start":"312","end":"317"},
      {"lyric":"流れる淚を時代の風に重ねて","start":"317","end":"330"},
      {"lyric":"終わらない貴方の吐息を感じて","start":"330","end":"341"},
      {"lyric":"Dry your tears with love","start":"341","end":"347"},
      {"lyric":"Dry your tears with love","start":"347","end":"354"},
      {"lyric":"Dry your tears with love","start":"354","end":"360"},
      {"lyric":"Dry your tears with love","start":"360","end":"423"}
    ]},
    //9
    {"title": "残酷な天使", "lines": []},
    //10
    {"title": "残酷な天使", "lines": []},
    //11
    {"title": "残酷な天使", "lines": []},
    //12
    {"title": "残酷な天使", "lines": []},
    //13
    {"title": "残酷な天使", "lines": []},
    //14
    {"title": "残酷な天使", "lines": []},
    //15
    {"title": "残酷な天使", "lines": []},
    //16
    {"title": "残酷な天使", "lines": []},
    //17
    {"title": "残酷な天使", "lines": []},
    //18
    {"title": "残酷な天使", "lines": []},
    //19
    {"title": "恋", "lines": [
      {"lyric":"営みの街が暮れたら色めき","start":"0","end":"20"},
      {"lyric":"風たちは運ぶわカラスと人々の群れ","start":"20","end":"26"},
      {"lyric":"意味なんかないさ暮らしがあるだけ","start":"26","end":"32"},
      {"lyric":"ただ腹を空かせて君の元へ帰るんだ","start":"32","end":"38"},
      {"lyric":"物心ついたらふと見上げて思うことが","start":"38","end":"44"},
      {"lyric":"この世にいる誰も二人から","start":"44","end":"50"},
      {"lyric":"胸の中にあるものいつか見えなくなるもの","start":"50","end":"56"},
      {"lyric":"それは側にいることいつも思い出して","start":"56","end":"62"},
      {"lyric":"君の中にあるもの距離の中にある鼓動","start":"62","end":"68"},
      {"lyric":"恋をしたの貴方の","start":"68","end":"71"},
      {"lyric":"指の混ざり頬の香り","start":"71","end":"75"},
      {"lyric":"夫婦を超えてゆけ","start":"75","end":"90"},
      {"lyric":"みにくいと秘めた想いは色づき","start":"90","end":"96"},
      {"lyric":"白鳥は運ぶわ当たり前を変えながら","start":"96","end":"102"},
      {"lyric":"恋せずにいられないな似た顔も虚構にも","start":"102","end":"108"},
      {"lyric":"愛が生まれるのは一人から","start":"108","end":"114"},
      {"lyric":"胸の中にあるものいつか見えなくなるもの","start":"114","end":"120"},
      {"lyric":"それは側にいることいつも思い出して","start":"120","end":"126"},
      {"lyric":"君の中にあるもの距離の中にある鼓動","start":"126","end":"132"},
      {"lyric":"恋をしたの貴方の","start":"132","end":"135"},
      {"lyric":"指の混ざり頬の香り","start":"135","end":"139"},
      {"lyric":"夫婦を超えてゆけ","start":"139","end":"166"},
      {"lyric":"泣き顔も黙る夜も","start":"166","end":"172"},
      {"lyric":"揺れる笑顔も","start":"172","end":"175"},
      {"lyric":"いつまでもいつまでも","start":"175","end":"181"},
      {"lyric":"胸の中にあるものいつか見えなくなるもの","start":"181","end":"187"},
      {"lyric":"それは側にいることいつも思い出して","start":"187","end":"193"},
      {"lyric":"君の中にあるもの距離の中にある鼓動","start":"193","end":"199"},
      {"lyric":"恋をしたの貴方の","start":"199","end":"202"},
      {"lyric":"指の混ざり頬の香り","start":"202","end":"205"},
      {"lyric":"夫婦を超えてゆけ","start":"205","end":"208"},
      {"lyric":"二人を超えてゆけ","start":"208","end":"211"},
      {"lyric":"一人を超えてゆけ","start":"211","end":"251"}
    ]},
    //20
    {"title": "One Love", "lines": [
      {"lyric":"伝えたくて伝わらなくて","start":"0","end":"38"},
      {"lyric":"時には素直になれずに","start":"38","end":"42"},
      {"lyric":"泣いた季節を越えた僕らは","start":"42","end":"47"},
      {"lyric":"今とても輝いてるよ","start":"47","end":"51"},
      {"lyric":"それぞれ描く幸せのカタチは重なり","start":"51","end":"58"},
      {"lyric":"今大きな愛になる","start":"58","end":"62"},
      {"lyric":"ずっとふたりで生きて行こう","start":"62","end":"70"},
      {"lyric":"百年先も愛を誓うよ","start":"70","end":"74"},
      {"lyric":"君は僕のすべてさ","start":"74","end":"79"},
      {"lyric":"信じている　ただ信じてる","start":"79","end":"84"},
      {"lyric":"同じ時を刻む人へ","start":"84","end":"89"},
      {"lyric":"どんな君も どんな僕でも","start":"89","end":"93"},
      {"lyric":"ひとつひとつが愛しい","start":"93","end":"98"},
      {"lyric":"君がいれば何もいらない","start":"98","end":"103"},
      {"lyric":"きっと幸せにするから","start":"103","end":"122"},
      {"lyric":"雨の中で君を待ってた","start":"122","end":"127"},
      {"lyric":"優しさの意味さえ知らず","start":"127","end":"131"},
      {"lyric":"すれ違いに傷ついた夜","start":"131","end":"136"},
      {"lyric":"それでもここまで来たんだ","start":"136","end":"140"},
      {"lyric":"掛け替えのない出逢い","start":"140","end":"143"},
      {"lyric":"弱い奇跡をつないでく","start":"143","end":"147"},
      {"lyric":"想い出重なり合う","start":"147","end":"150"},
      {"lyric":"始まりの歌鳴り響いて","start":"150","end":"159"},
      {"lyric":"どんな時も支えてくれた","start":"159","end":"163"},
      {"lyric":"笑い泣いた仲間へ","start":"163","end":"168"},
      {"lyric":"心こめてただ一つだけ","start":"168","end":"173"},
      {"lyric":"送る言葉は「ありがとう。」","start":"173","end":"198"},
      {"lyric":"百年先も愛を誓うよ","start":"198","end":"203"},
      {"lyric":"君は僕のすべてさ","start":"203","end":"208"},
      {"lyric":"愛しているただ愛してる","start":"208","end":"212"},
      {"lyric":"同じ明日約束しよう","start":"212","end":"217"},
      {"lyric":"世界中にただ一人だけ","start":"217","end":"222"},
      {"lyric":"僕は君を選んだ","start":"222","end":"226"},
      {"lyric":"君といればどんな未来も","start":"226","end":"231"},
      {"lyric":"ずっと輝いているから","start":"231","end":"238"},
      {"lyric":"lalala~","start":"238","end":"284"}
    ]},
    //21
    {"title": "残酷な天使", "lines": []},
    //22
    {"title": "世界はそれを愛と呼ぶんだぜ ", "lines": [
      {"lyric":"淚の中にかすかな光りがともったら","start":"0","end":"44"},
      {"lyric":"君の目の前であたためてた事話すのさ","start":"44","end":"51"},
      {"lyric":"それでも僕等の聲が乾いてゆくだけなら","start":"51","end":"58"},
      {"lyric":"朝が來るまでせめて誰かと歌いたいんだ","start":"58","end":"66"},
      {"lyric":"昨日のあなたが偽だと言うなら","start":"66","end":"73"},
      {"lyric":"昨日の景色を捨てちまうだけだ","start":"73","end":"79"},
      {"lyric":"新しい日日を繫ぐのは","start":"79","end":"82"},
      {"lyric":"新しい君と僕なのさ","start":"82","end":"85"},
      {"lyric":"僕らなぜか確かめ合う","start":"85","end":"89"},
      {"lyric":"世界じゃそれを愛と呼ぶんだぜ","start":"89","end":"94"},
      {"lyric":"心の聲を繫ぐのが","start":"94","end":"96"},
      {"lyric":"これ程怖いモノだとは","start":"96","end":"99"},
      {"lyric":"君と僕が聲を合わす","start":"99","end":"104"},
      {"lyric":"今までの過去なんて","start":"104","end":"107"},
      {"lyric":"なかったかのように歌い出すんだ","start":"107","end":"114"},
      {"lyric":"僕らはいずれ誰かを疑っちまうから","start":"114","end":"121"},
      {"lyric":"せめて今だけ美しい歌を歌うのさ","start":"121","end":"127"},
      {"lyric":"悲しい言葉では","start":"127","end":"132"},
      {"lyric":"何も變わらないだぜ","start":"132","end":"136"},
      {"lyric":"ヤツらが何をしたっていうんだ","start":"136","end":"140"},
      {"lyric":"昨日のあなたが裏切りの人なら","start":"140","end":"147"},
      {"lyric":"昨日の景色を忘れちまうんだけだ","start":"147","end":"153"},
      {"lyric":"新しい日日を變えるのは","start":"153","end":"157"},
      {"lyric":"いじらしいほどの愛なのさ","start":"157","end":"160"},
      {"lyric":"僕らそれを確かめ合う","start":"160","end":"163"},
      {"lyric":"世界じゃそれも愛と呼ぶんだぜ","start":"163","end":"167"},
      {"lyric":"心の聲を繫ぐのが","start":"167","end":"170"},
      {"lyric":"これほど怖いものだとは","start":"170","end":"173"},
      {"lyric":"僕らなぜか聲を合わす","start":"173","end":"177"},
      {"lyric":"今までの過去なんて","start":"177","end":"180"},
      {"lyric":"なかったかのように歌い出すんだぜ","start":"180","end":"223"},
      {"lyric":"愛と平和!","start":"223","end":"227"},
      {"lyric":"愛と平和!","start":"227","end":"230"},
      {"lyric":"愛と平和!","start":"230","end":"232"},
      {"lyric":"悲しみで花がさくものか!","start":"232","end":"236"},
      {"lyric":"新しい日日の僕たちは高鳴る予感がしてるのさ","start":"236","end":"242"},
      {"lyric":"君と僕が夢を叫ぶ","start":"242","end":"246"},
      {"lyric":"世界はそれを待っているんだぜ","start":"246","end":"250"},
      {"lyric":"あなたのために歌うのが","start":"250","end":"254"},
      {"lyric":"これほど布いものだとは","start":"254","end":"257"},
      {"lyric":"だけど僕ら確かめ合う","start":"257","end":"260"},
      {"lyric":"今までの過去なんてなかったかのように","start":"260","end":"267"},
      {"lyric":"悲しみの夜なんて","start":"267","end":"270"},
      {"lyric":"なかったかのように歌い出すんだぜ","start":"270","end":"288"},
      {"lyric":"世界じゃそれを愛と呼ぶんだぜ","start":"288","end":"321"}
    ]}
  ]
}
